{"uuid": "de359a01-0fb7-4e6a-a36c-b1c6369417fa", "children": ["160c9f82-7720-4246-a7fd-2742caa0d780"], "befores": [{"name": "before_test", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=126.0.6478.185)\nStacktrace:\n\tGetHandleVerifier [0x00007FF72136EEB2+31554]\n\t(No symbol) [0x00007FF7212E7EE9]\n\t(No symbol) [0x00007FF7211A872A]\n\t(No symbol) [0x00007FF72117D995]\n\t(No symbol) [0x00007FF7212244D7]\n\t(No symbol) [0x00007FF72123C051]\n\t(No symbol) [0x00007FF72121CDD3]\n\t(No symbol) [0x00007FF7211EA33B]\n\t(No symbol) [0x00007FF7211EAED1]\n\tGetHandleVerifier [0x00007FF721678B2D+3217341]\n\tGetHandleVerifier [0x00007FF7216C5AF3+3532675]\n\tGetHandleVerifier [0x00007FF7216BB0F0+3489152]\n\tGetHandleVerifier [0x00007FF72141E786+750614]\n\t(No symbol) [0x00007FF7212F376F]\n\t(No symbol) [0x00007FF7212EEB24]\n\t(No symbol) [0x00007FF7212EECB2]\n\t(No symbol) [0x00007FF7212DE17F]\n\tBaseThreadInitThunk [0x00007FFC13A27374+20]\n\tRtlUserThreadStart [0x00007FFC1485CC91+33]\n\n", "trace": "  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"G:\\selenium_python\\selenium-python\\selenium-python-main\\tests\\test_base.py\", line 13, in before_test\n    Selenium.close_notification()\n  File \"G:\\selenium_python\\selenium-python\\selenium-python-main\\src\\automation\\__init__.py\", line 25, in close_notification\n    return Selenium.driver.close_notification()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"G:\\selenium_python\\selenium-python\\selenium-python-main\\src\\automation\\driver\\__init__.py\", line 46, in close_notification\n    close_button = WebDriverWait(self._driver, 10).until(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 96, in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 363, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\trung.dang\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721990608552, "stop": 1721990620647}], "start": 1721990608552, "stop": 1721990624842}